### ISSUE TITLE
希望归入另一个开源项目

### ISSUE THREAD

**Issue by Atomseek** [Columbium626/Log-on-campus-network-of-GuangxiUniversity#1]
https://github.com/gxuwc/gxuwc

**Comment by sorbose** [comment]
可以的，不过这个脚本写的非常简单，可能没有太多帮助

**Comment by sorbose** [comment]
可以的，不过这个脚本写的非常简单，可能没有太多帮助

**Comment by Atomseek** [comment]
> 
> 
> 可以的，不过这个脚本写的非常简单，可能没有太多帮助

没关系，都是边学编写
